### ISSUE TITLE
Remove bootstrap mode from the first server after others have joined

### ISSUE THREAD

**Issue by lewis-carhart** [edigitalresearch/ansible-role-consul#11]
"Currently, since server1 was started in bootstrap mode, it has the power to make decisions without consulting the other servers. Since they are supposed to operate as equals and make decisions by quorum, we want to remove this privilege after the cluster has been bootstrapped."

Source: https://www.digitalocean.com/community/tutorials/an-introduction-to-using-consul-a-service-discovery-system-on-ubuntu-14-04

Which is an old article but it is worth looking into this further to see if it is therefore possible for one server to make decisions on its own.

**Comment by lewis-carhart** [comment]
Ping @maruedr-dylanrhysscott

**Comment by maruedr-dylanrhysscott** [comment]
PR open @lewis-carhart
